name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'

jobs:
  publish_to_pypi:
    name: Push Package to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Set up Python
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install build

      - name: Build package
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@b7f401de30cb6434a1e19f805ff006643653240e
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
